"""
make_cbp.py - generate Code::Blocks projects for the reference code.

Run it (no arguments needed):

    python make_cbp.py

It scans this folder recursively and, for every folder containing a main.cpp
(the worked_examples/ and past_assessments/ solutions), writes:
  - <folder_name>.cbp            one Code::Blocks project per problem/solution
And in this folder it writes:
  - exam_reference.workspace      opens them all at once in Code::Blocks

These are STUDY examples. The project you actually code in during an assessment
is ../exam_workspace/ (open exam_workspace.cbp there).

Special handling: if a .cpp file is #included by another file in the same
folder (e.g. main.cpp has  #include "unsortedtype.cpp"  for templates), that
.cpp is added to the project tree but marked NOT to compile/link on its own.
"""

from pathlib import Path
import re
import xml.sax.saxutils as xml_escape

HERE = Path(__file__).parent.resolve()
WORKSPACE_NAME = "exam_reference"
GENERATED_MARKER = "<!-- AUTO-GENERATED BY make_cbp.py -->"

CPP_EXTENSIONS = {".cpp", ".cxx", ".cc", ".c"}
HEADER_EXTENSIONS = {".h", ".hpp"}
IGNORE_DIRS = {".git", ".vscode", "bin", "obj", "__pycache__"}

INCLUDE_RE = re.compile(r'#\s*include\s*"([^"]+)"')


def safe_xml(text: str) -> str:
    return xml_escape.escape(text)


def clean_project_name(name: str) -> str:
    return name.replace(" ", "_")


def find_project_dirs(root: Path):
    """Every folder that directly contains a main.cpp becomes one project."""
    project_dirs = []
    for main_file in root.rglob("main.cpp"):
        if any(part in IGNORE_DIRS for part in main_file.relative_to(root).parts):
            continue
        project_dirs.append(main_file.parent)
    return sorted(project_dirs)


def get_source_units(project_dir: Path):
    """All .cpp/.h files directly inside the folder."""
    units = []
    for file in sorted(project_dir.iterdir()):
        if not file.is_file():
            continue
        if file.suffix.lower() in CPP_EXTENSIONS | HEADER_EXTENSIONS:
            units.append(file.name)
    return units


def find_included_cpps(project_dir: Path):
    """Names of .cpp files #include-d by another file here (do not compile them)."""
    included = set()
    for file in project_dir.iterdir():
        if not file.is_file() or file.suffix.lower() not in CPP_EXTENSIONS | HEADER_EXTENSIONS:
            continue
        try:
            text = file.read_text(encoding="utf-8", errors="ignore")
        except OSError:
            continue
        for target in INCLUDE_RE.findall(text):
            target_name = Path(target).name
            if target_name.lower().endswith(tuple(CPP_EXTENSIONS)):
                included.add(target_name)
    return included


def unit_xml_line(unit: str, included_cpps: set) -> str:
    if unit in included_cpps:
        return (
            f'\t\t<Unit filename="{safe_xml(unit)}">\n'
            f'\t\t\t<Option compile="0" />\n'
            f'\t\t\t<Option link="0" />\n'
            f'\t\t</Unit>'
        )
    return f'\t\t<Unit filename="{safe_xml(unit)}" />'


def make_cbp(project_dir: Path) -> Path:
    project_name = clean_project_name(project_dir.name)
    cbp_path = project_dir / f"{project_name}.cbp"

    units = get_source_units(project_dir)
    included_cpps = find_included_cpps(project_dir)
    unit_xml = "\n".join(unit_xml_line(u, included_cpps) for u in units)

    cbp_content = f'''<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
{GENERATED_MARKER}
<CodeBlocks_project_file>
\t<FileVersion major="1" minor="6" />
\t<Project>
\t\t<Option title="{safe_xml(project_name)}" />
\t\t<Option pch_mode="2" />
\t\t<Option compiler="gcc" />

\t\t<Build>
\t\t\t<Target title="Debug">
\t\t\t\t<Option output="bin/Debug/{safe_xml(project_name)}" prefix_auto="1" extension_auto="1" />
\t\t\t\t<Option object_output="obj/Debug/" />
\t\t\t\t<Option type="1" />
\t\t\t\t<Option compiler="gcc" />
\t\t\t\t<Compiler>
\t\t\t\t\t<Add option="-g" />
\t\t\t\t</Compiler>
\t\t\t</Target>

\t\t\t<Target title="Release">
\t\t\t\t<Option output="bin/Release/{safe_xml(project_name)}" prefix_auto="1" extension_auto="1" />
\t\t\t\t<Option object_output="obj/Release/" />
\t\t\t\t<Option type="1" />
\t\t\t\t<Option compiler="gcc" />
\t\t\t\t<Compiler>
\t\t\t\t\t<Add option="-O2" />
\t\t\t\t</Compiler>
\t\t\t\t<Linker>
\t\t\t\t\t<Add option="-s" />
\t\t\t\t</Linker>
\t\t\t</Target>
\t\t</Build>

\t\t<Compiler>
\t\t\t<Add option="-std=c++17" />
\t\t\t<Add option="-Wall" />
\t\t\t<Add option="-fexceptions" />
\t\t</Compiler>

{unit_xml}

\t\t<Extensions>
\t\t\t<code_completion />
\t\t\t<envvars />
\t\t\t<debugger />
\t\t</Extensions>
\t</Project>
</CodeBlocks_project_file>
'''

    cbp_path.write_text(cbp_content, encoding="utf-8")
    return cbp_path


def make_workspace(cbp_files) -> Path:
    workspace_path = HERE / f"{WORKSPACE_NAME}.workspace"

    project_lines = []
    for index, cbp in enumerate(cbp_files):
        relative_path = cbp.relative_to(HERE).as_posix()
        active = ' active="1"' if index == 0 else ""
        project_lines.append(
            f'\t\t<Project filename="{safe_xml(relative_path)}"{active} />'
        )

    workspace_content = f'''<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
{GENERATED_MARKER}
<CodeBlocks_workspace_file>
\t<Workspace title="{WORKSPACE_NAME}">
{chr(10).join(project_lines)}
\t</Workspace>
</CodeBlocks_workspace_file>
'''

    workspace_path.write_text(workspace_content, encoding="utf-8")
    return workspace_path


def main():
    project_dirs = find_project_dirs(HERE)
    if not project_dirs:
        print("No folders with a main.cpp were found.")
        return

    cbp_files = []
    for project_dir in project_dirs:
        cbp = make_cbp(project_dir)
        cbp_files.append(cbp)
        print(f"  project:   {cbp.relative_to(HERE)}")

    workspace = make_workspace(cbp_files)
    print(f"  workspace: {workspace.relative_to(HERE)}")

    print("\nDone. In Code::Blocks either:")
    print(f"  - open {WORKSPACE_NAME}.workspace to load everything, or")
    print("  - open one <folder>/<folder>.cbp and press F9 to build & run.")


if __name__ == "__main__":
    main()
