from pathlib import Path
import xml.sax.saxutils as xml_escape

ROOT = Path(__file__).parent.resolve()
GENERATED_MARKER = "<!-- AUTO-GENERATED BY make_codeblocks_workspaces.py -->"

CPP_EXTENSIONS = {".cpp", ".cxx", ".cc", ".c"}
HEADER_EXTENSIONS = {".h", ".hpp"}

IGNORE_DIRS = {
    ".git",
    ".vscode",
    "bin",
    "obj",
    "__pycache__",
}


def safe_xml(text: str) -> str:
    return xml_escape.escape(text)


def clean_project_name(name: str) -> str:
    return name.replace(" ", "_")


def has_ignored_part(path: Path) -> bool:
    return any(part in IGNORE_DIRS for part in path.parts)


def is_lab_folder(folder: Path) -> bool:
    """
    A lab folder is something like lab01, lab02, lab03.
    """
    name = folder.name.lower()
    return name.startswith("lab") and name[3:].isdigit()


def find_lab_folders(root: Path):
    lab_folders = []

    for folder in sorted(root.iterdir()):
        if folder.is_dir() and is_lab_folder(folder):
            lab_folders.append(folder)

    return lab_folders


def find_project_dirs(lab_folder: Path):
    """
    Each folder containing a main.cpp becomes one Code::Blocks project.
    """
    project_dirs = []

    for main_file in lab_folder.rglob("main.cpp"):
        relative = main_file.relative_to(lab_folder)

        if has_ignored_part(relative):
            continue

        project_dirs.append(main_file.parent)

    return sorted(project_dirs)


def get_units(project_dir: Path):
    """
    Add all .cpp/.h files directly inside the task folder.
    """
    units = []

    for file in sorted(project_dir.iterdir()):
        if not file.is_file():
            continue

        if file.suffix.lower() in CPP_EXTENSIONS | HEADER_EXTENSIONS:
            units.append(file.name)

    return units


def make_cbp(project_dir: Path):
    project_name = clean_project_name(project_dir.name)
    cbp_path = project_dir / f"{project_name}.cbp"
    units = get_units(project_dir)

    unit_xml = "\n".join(
        f'\t\t<Unit filename="{safe_xml(unit)}" />'
        for unit in units
    )

    cbp_content = f'''<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
{GENERATED_MARKER}
<CodeBlocks_project_file>
\t<FileVersion major="1" minor="6" />
\t<Project>
\t\t<Option title="{safe_xml(project_name)}" />
\t\t<Option pch_mode="2" />
\t\t<Option compiler="gcc" />

\t\t<Build>
\t\t\t<Target title="Debug">
\t\t\t\t<Option output="bin/Debug/{safe_xml(project_name)}" prefix_auto="1" extension_auto="1" />
\t\t\t\t<Option object_output="obj/Debug/" />
\t\t\t\t<Option type="1" />
\t\t\t\t<Option compiler="gcc" />
\t\t\t\t<Compiler>
\t\t\t\t\t<Add option="-g" />
\t\t\t\t</Compiler>
\t\t\t</Target>

\t\t\t<Target title="Release">
\t\t\t\t<Option output="bin/Release/{safe_xml(project_name)}" prefix_auto="1" extension_auto="1" />
\t\t\t\t<Option object_output="obj/Release/" />
\t\t\t\t<Option type="1" />
\t\t\t\t<Option compiler="gcc" />
\t\t\t\t<Compiler>
\t\t\t\t\t<Add option="-O2" />
\t\t\t\t</Compiler>
\t\t\t\t<Linker>
\t\t\t\t\t<Add option="-s" />
\t\t\t\t</Linker>
\t\t\t</Target>
\t\t</Build>

\t\t<Compiler>
\t\t\t<Add option="-Wall" />
\t\t\t<Add option="-fexceptions" />
\t\t</Compiler>

{unit_xml}

\t\t<Extensions>
\t\t\t<code_completion />
\t\t\t<envvars />
\t\t\t<debugger />
\t\t</Extensions>
\t</Project>
</CodeBlocks_project_file>
'''

    cbp_path.write_text(cbp_content, encoding="utf-8")
    return cbp_path


def make_lab_workspace(lab_folder: Path, cbp_files):
    workspace_path = lab_folder / f"{lab_folder.name}.workspace"

    project_lines = []
    for index, cbp in enumerate(cbp_files):
        relative_path = cbp.relative_to(lab_folder).as_posix()
        active = ' active="1"' if index == 0 else ""
        project_lines.append(
            f'\t\t<Project filename="{safe_xml(relative_path)}"{active} />'
        )

    workspace_content = f'''<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
{GENERATED_MARKER}
<CodeBlocks_workspace_file>
\t<Workspace title="{safe_xml(lab_folder.name)}">
{chr(10).join(project_lines)}
\t</Workspace>
</CodeBlocks_workspace_file>
'''

    workspace_path.write_text(workspace_content, encoding="utf-8")
    return workspace_path


def remove_stale_generated_cbp(lab_folder: Path, valid_cbp_paths):
    valid_cbp_paths = {path.resolve() for path in valid_cbp_paths}

    for cbp in lab_folder.rglob("*.cbp"):
        if has_ignored_part(cbp.relative_to(lab_folder)):
            continue

        if cbp.resolve() in valid_cbp_paths:
            continue

        try:
            content = cbp.read_text(encoding="utf-8", errors="ignore")
        except OSError:
            continue

        if GENERATED_MARKER in content:
            cbp.unlink()
            print(f"Removed stale project: {cbp.relative_to(ROOT)}")


def main():
    lab_folders = find_lab_folders(ROOT)

    if not lab_folders:
        print("No lab folders found. Expected folders like lab01, lab02, lab03.")
        return

    for lab_folder in lab_folders:
        print(f"\nScanning {lab_folder.name}...")

        project_dirs = find_project_dirs(lab_folder)

        if not project_dirs:
            print(f"  No task folders with main.cpp found in {lab_folder.name}.")
            continue

        cbp_files = []

        for project_dir in project_dirs:
            cbp = make_cbp(project_dir)
            cbp_files.append(cbp)
            print(f"  Created/updated project: {cbp.relative_to(ROOT)}")

        remove_stale_generated_cbp(lab_folder, cbp_files)

        workspace = make_lab_workspace(lab_folder, cbp_files)
        print(f"  Created/updated workspace: {workspace.relative_to(ROOT)}")

    print("\nDone.")
    print("Open the specific lab workspace in Code::Blocks, such as:")
    print("  lab01/lab01.workspace")
    print("  lab02/lab02.workspace")
    print("  lab03/lab03.workspace")


if __name__ == "__main__":
    main()
