"""
make_cbp.py  --  (re)generate the Code::Blocks project for THIS folder.

Run it whenever you add or rename files in the project:

    python make_cbp.py

It writes exam_workspace.cbp (named after this folder) that:
  - compiles main.cpp,
  - lists every .h under the folder in the project tree so you
    can open them in Code::Blocks,
  - marks any .cpp that is #include-d by another file as "do not compile"
    (the template  #include "foo.cpp"  pattern), so no duplicate/linker errors.

Then open exam_workspace.cbp in Code::Blocks and press F9 to build & run.
"""

from pathlib import Path
import re
import xml.sax.saxutils as xml_escape

HERE = Path(__file__).parent.resolve()
PROJECT_NAME = HERE.name.replace(" ", "_")
GENERATED_MARKER = "<!-- AUTO-GENERATED BY make_cbp.py -->"

CPP_EXTENSIONS = {".cpp", ".cxx", ".cc", ".c"}
HEADER_EXTENSIONS = {".h", ".hpp"}
IGNORE_DIRS = {".git", ".vscode", "bin", "obj", "__pycache__"}

INCLUDE_RE = re.compile(r'#\s*include\s*"([^"]+)"')


def safe_xml(text: str) -> str:
    return xml_escape.escape(text)


def in_ignored_dir(path: Path) -> bool:
    return any(part in IGNORE_DIRS for part in path.relative_to(HERE).parts)


def collect_files():
    """Return (source_units, header_units) as forward-slash relative paths."""
    sources, headers = [], []
    for f in sorted(HERE.rglob("*")):
        if not f.is_file() or in_ignored_dir(f):
            continue
        rel = f.relative_to(HERE).as_posix()
        ext = f.suffix.lower()
        if ext in CPP_EXTENSIONS:
            sources.append(rel)
        elif ext in HEADER_EXTENSIONS:
            headers.append(rel)
    return sources, headers


def find_included_cpps():
    """Names of .cpp files that are #include-d by some other file here."""
    included = set()
    for f in HERE.rglob("*"):
        if not f.is_file() or in_ignored_dir(f):
            continue
        if f.suffix.lower() not in CPP_EXTENSIONS | HEADER_EXTENSIONS:
            continue
        try:
            text = f.read_text(encoding="utf-8", errors="ignore")
        except OSError:
            continue
        for target in INCLUDE_RE.findall(text):
            if target.lower().endswith(tuple(CPP_EXTENSIONS)):
                included.add(Path(target).name)
    return included


def unit_line(rel_path: str, no_compile: bool) -> str:
    if no_compile:
        return (
            f'\t\t<Unit filename="{safe_xml(rel_path)}">\n'
            f'\t\t\t<Option compile="0" />\n'
            f'\t\t\t<Option link="0" />\n'
            f'\t\t</Unit>'
        )
    return f'\t\t<Unit filename="{safe_xml(rel_path)}" />'


def main():
    sources, headers = collect_files()
    if "main.cpp" not in sources:
        print("Warning: no main.cpp in this folder; the project will not run.")

    included_cpps = find_included_cpps()

    lines = []
    for src in sources:
        lines.append(unit_line(src, Path(src).name in included_cpps))
    for hdr in headers:                       # headers are never compiled units
        lines.append(unit_line(hdr, False))
    unit_xml = "\n".join(lines)

    cbp = f'''<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
{GENERATED_MARKER}
<CodeBlocks_project_file>
\t<FileVersion major="1" minor="6" />
\t<Project>
\t\t<Option title="{safe_xml(PROJECT_NAME)}" />
\t\t<Option pch_mode="2" />
\t\t<Option compiler="gcc" />

\t\t<Build>
\t\t\t<Target title="Debug">
\t\t\t\t<Option output="bin/Debug/{safe_xml(PROJECT_NAME)}" prefix_auto="1" extension_auto="1" />
\t\t\t\t<Option object_output="obj/Debug/" />
\t\t\t\t<Option type="1" />
\t\t\t\t<Option compiler="gcc" />
\t\t\t\t<Compiler>
\t\t\t\t\t<Add option="-g" />
\t\t\t\t</Compiler>
\t\t\t</Target>

\t\t\t<Target title="Release">
\t\t\t\t<Option output="bin/Release/{safe_xml(PROJECT_NAME)}" prefix_auto="1" extension_auto="1" />
\t\t\t\t<Option object_output="obj/Release/" />
\t\t\t\t<Option type="1" />
\t\t\t\t<Option compiler="gcc" />
\t\t\t\t<Compiler>
\t\t\t\t\t<Add option="-O2" />
\t\t\t\t</Compiler>
\t\t\t\t<Linker>
\t\t\t\t\t<Add option="-s" />
\t\t\t\t</Linker>
\t\t\t</Target>
\t\t</Build>

\t\t<Compiler>
\t\t\t<Add option="-std=c++17" />
\t\t\t<Add option="-Wall" />
\t\t\t<Add option="-fexceptions" />
\t\t</Compiler>

{unit_xml}

\t\t<Extensions>
\t\t\t<code_completion />
\t\t\t<envvars />
\t\t\t<debugger />
\t\t</Extensions>
\t</Project>
</CodeBlocks_project_file>
'''

    out = HERE / f"{PROJECT_NAME}.cbp"
    out.write_text(cbp, encoding="utf-8")
    print(f"Wrote {out.name}")
    print(f"  sources: {', '.join(sources) or '(none)'}")
    print(f"  headers: {', '.join(headers) or '(none)'}")
    if included_cpps:
        print(f"  not compiled (included .cpp): {', '.join(sorted(included_cpps))}")
    print(f"\nOpen {out.name} in Code::Blocks and press F9.")


if __name__ == "__main__":
    main()
